config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations'}

  scope "/admin" do
    resources :users
  end

  resources :roles

  root to: "home#index"

  resources :inspections
  resources :buildings do 
    resources :units
  end
  resources :inspection_templates
  

end

app/models/building.rb
class Building < ActiveRecord::Base
	scope :recent_buildings, ->(current_user) { where(user: current_user).last(5) }

	has_many :units
	belongs_to :user

	mount_uploaders :photos, BuildingPhotosUploader

	validates :name, :address_line_1, :zip, :city, :state, presence: true
	geocoded_by :full_address
	after_validation :geocode, if: :address_fields_changed?


	def full_address
		[address_line_1, city, zip, state].compact.join(',')
	end

	def address_fields_changed?
		attrs = %w(address_line_1 city state zip)
  	attrs.any?{|a| send "#{a}_changed?"}
  end

end

app/controllers/buildings_controller.rb
class BuildingsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_building, only: [:show, :edit, :update, :destroy]

  authorize_resource

  # GET /buildings
  # GET /buildings.json
  def index
    @buildings = Building.where(user: current_user)
  end

  # GET /buildings/1
  # GET /buildings/1.json
  def show
  end

  # GET /buildings/new
  def new
    @building = Building.new
  end

  # GET /buildings/1/edit
  def edit
  end

  # POST /buildings
  # POST /buildings.json
  def create
    @building = Building.new(building_params)
    @building.user = current_user

    respond_to do |format|
      if @building.save
        format.html { redirect_to @building, notice: 'Building was successfully created.' }
        format.json { render :show, status: :created, location: @building }
      else
        format.html { render :new }
        format.json { render :json => { :error =>  @building.errors.full_messages }, :status => 422 }
      end
    end
  end

  # PATCH/PUT /buildings/1
  # PATCH/PUT /buildings/1.json
  def update
    respond_to do |format|
      if @building.update(building_params)
        format.html { redirect_to @building, notice: 'Building was successfully updated.' }
        format.json { render :show, status: :ok, location: @building }
      else
        format.html { render :edit }
        format.json { render json: @building.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /buildings/1
  # DELETE /buildings/1.json
  def destroy
    @building.destroy
    respond_to do |format|
      format.html { redirect_to buildings_url, notice: 'Building was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_building
      @building = Building.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def building_params
      params.require(:building).permit(:name, :address_line_1, :address_line_2, :city, :state, :zip, :latitude, :longitude)
    end
end

app/helpers/buildings_helper.rb
module BuildingsHelper
end

app/views/buildings/_form.html.erb
<%= form_for(@building) do |f| %>
  <% if @building.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@building.errors.count, "error") %> prohibited this building from being saved:</h2>

      <ul>
      <% @building.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :address_line_1 %><br>
    <%= f.text_field :address_line_1 %>
  </div>
  <div class="field">
    <%= f.label :address_line_2 %><br>
    <%= f.text_field :address_line_2 %>
  </div>
  <div class="field">
    <%= f.label :city %><br>
    <%= f.text_field :city %>
  </div>
  <div class="field">
    <%= f.label :state %><br>
    <%= f.text_field :state %>
  </div>
  <div class="field">
    <%= f.label :zip %><br>
    <%= f.text_field :zip %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/buildings/edit.html.erb
<h1>Editing Building</h1>

<%= render 'form' %>

<%= link_to 'Show', @building %> |
<%= link_to 'Back', buildings_path %>

app/views/buildings/index.html.erb
<h1>Listing Buildings</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address line 1</th>
      <th>Address line 2</th>
      <th>City</th>
      <th>State</th>
      <th>Zip</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @buildings.each do |building| %>
      <tr>
        <td><%= building.name %></td>
        <td><%= building.address_line_1 %></td>
        <td><%= building.address_line_2 %></td>
        <td><%= building.city %></td>
        <td><%= building.state %></td>
        <td><%= building.zip %></td>
        <td><%= link_to 'Show', building %></td>
        <td><%= link_to 'Edit', edit_building_path(building) %></td>
        <td><%= link_to 'Destroy', building, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Building', new_building_path %>

app/views/buildings/new.html.erb
<h1>New Building</h1>

<%= render 'form' %>

<%= link_to 'Back', buildings_path %>

app/views/buildings/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @building.name %>
</p>

<p>
  <strong>Address line 1:</strong>
  <%= @building.address_line_1 %>
</p>

<p>
  <strong>Address line 2:</strong>
  <%= @building.address_line_2 %>
</p>

<p>
  <strong>City:</strong>
  <%= @building.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @building.state %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @building.zip %>
</p>

<%= link_to 'Edit', edit_building_path(@building) %> |
<%= link_to 'Back', buildings_path %>