config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations'}

  scope "/admin" do
    resources :users
  end

  resources :roles

  root to: "home#index"

  resources :inspections
  resources :buildings do 
    resources :units
  end
  resources :inspection_templates
  

end

app/models/unit.rb
class Unit < ActiveRecord::Base
  validates :unit_number, presence: true

  belongs_to :building

  validates :building, presence: true
end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_building


  # GET /units
  # GET /units.json
  def index
    @units = @building.units
  end

  # GET /units/1
  # GET /units/1.json
  def show
    set_unit
    authorize! :read, @unit
  end

  # GET /units/new
  def new
    @unit = Unit.new
  end

  # GET /units/1/edit
  def edit
    set_unit
    authorize! :update, @unit
  end

  # POST /units
  # POST /units.json
  def create
    authorize! :update, @building

    @unit = @building.units.new(unit_params)

    respond_to do |format|
      if @unit.save
        format.html { redirect_to [@building, @unit], notice: 'Unit was successfully created.' }
        format.json { render :show, status: :created, location: [@building, @unit] }
      else
        format.html { render :new }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /units/1
  # PATCH/PUT /units/1.json
  def update
    set_unit

    authorize! :update, @unit

    respond_to do |format|
      if @unit.update(unit_params)
        format.html { redirect_to [@building, @unit], notice: 'Unit was successfully updated.' }
        format.json { render :show, status: :ok, location: [@building, @unit] }
      else
        format.html { render :edit }
        format.json { render json: @unit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /units/1
  # DELETE /units/1.json
  def destroy
    set_unit

    authorize! :destroy, @unit

    @unit.destroy
    respond_to do |format|
      format.html { redirect_to building_units_url(@building), notice: 'Unit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_unit
      @unit = @building.units.find(params[:id])
    end

    def set_building
      @building = Building.find(params[:building_id])
      authorize! :read, @building
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def unit_params
      params.require(:unit).permit(:building_id, :unit_number)
    end
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/views/units/_form.html.erb
<%= form_for([@building, @unit]) do |f| %>
  <% if @unit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@unit.errors.count, "error") %> prohibited this unit from being saved:</h2>

      <ul>
      <% @unit.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :building_id %><br>
    <%= f.text_field :building_id %>
  </div>
  <div class="field">
    <%= f.label :unit_number %><br>
    <%= f.text_field :unit_number %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/units/edit.html.erb
<h1>Editing Unit</h1>

<%= render 'form' %>

<%= link_to 'Show', @unit %> |
<%= link_to 'Back', units_path %>

app/views/units/index.html.erb
<h1>Listing Units</h1>

<table>
  <thead>
    <tr>
      <th>Building</th>
      <th>Unit number</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @units.each do |unit| %>
      <tr>
        <td><%= unit.building %></td>
        <td><%= unit.unit_number %></td>
        <td><%= link_to 'Show', [unit.building, unit] %></td>
        <td><%= link_to 'Edit', edit_building_unit_path(unit.building, unit) %></td>
        <td><%= link_to 'Destroy', building_unit_path(@building, unit), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Unit', new_building_unit_path(@building) %>

app/views/units/new.html.erb
<h1>New Unit</h1>

<%= render 'form' %>

<%= link_to 'Back', building_units_path(@building) %>

app/views/units/show.html.erb
<p>
  <strong>Building:</strong>
  <%= @unit.building %>
</p>

<p>
  <strong>Unit number:</strong>
  <%= @unit.unit_number %>
</p>

<%= link_to 'Edit', edit_building_unit_path(@building, @unit) %> |
<%= link_to 'Back', building_units_path(@building) %>