config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations'}

  scope "/admin" do
    resources :users
  end

  resources :roles

  root to: "home#index"

  resources :inspections
  resources :buildings do 
    resources :units
  end
  resources :inspection_templates
  

end

app/models/inspection.rb
class Inspection < ActiveRecord::Base
  attr_accessor :template_id
  scope :recent_inspections, ->(current_user) { where(user: current_user).last(5) }

  belongs_to :unit
  belongs_to :building
  belongs_to :user
  has_many :items, -> { order(position: :asc) }, 
    class_name: "Inspection::Item", 
    autosave: true, 
    dependent: :destroy

  serialize :sections, Array

  validates :unit, presence: true
  validates :building, presence: true
  validates :template_id, presence: true, on: :create
  validate :sections_are_unique

  before_validation :build_inspection_and_items_from_template, if: :new_record?

  accepts_nested_attributes_for :items

  def template=(template)
    @template_id = template.id if template
  end

  def template_id=(template_id)
    @template_id = template_id
  end

  def build_inspection_and_items_from_template
    template = InspectionTemplate.where(id: @template_id)

    template = template.first || return

    self.sections = template.sections

    return if items.count > 0 # Don't accidentally create the items twice

    if (template.items.count < 1)
      errors.add(:base, "Template has no items!")
      return
    end
    template.items.each do |template_item|
      new_item = Inspection::Item.build_from_template_item(template_item)
      new_item.inspection = self
      self.items << new_item
    end
  end

  def sections_are_unique
    if sections.uniq.length != sections.length
      errors.add(:sections, "are not unique")
    end
  end


end

app/models/inspection/item.rb
class Inspection::Item < ActiveRecord::Base
  belongs_to :inspection

  validates :name, :section, :position, :inspection, presence: true

  def self.build_from_template_item(template_item)    
    self.new(
      name: template_item.name,
      weight: template_item.weight,
      section: template_item.section,
      position: template_item.position,
      score_type: template_item.score_type)
  end

  # used in tests to check if this item is instantiated properly from its template
  def matches_template_item?(template_item)
    return false if template_item.nil?
    return false if self.name != template_item.name
    return false if self.section != template_item.section
    return false if self.weight != template_item.weight
    return false if self.position != template_item.position
    return false if self.score_type != template_item.score_type
    true
  end

  def score
    @score ||= Score.create(score_type, self.raw_score)
  end

  def score=(new_score)
    score.set_score new_score
    self.raw_score = score.raw_score
  end

end

app/controllers/inspections_controller.rb
class InspectionsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_inspection, only: [:show, :edit, :update, :destroy]

  authorize_resource

  # GET /inspections
  # GET /inspections.json
  def index
    @inspections = Inspection.where(user_id: current_user.id)
  end

  # GET /inspections/1
  # GET /inspections/1.json
  def show
  end

  # GET /inspections/new
  def new
    @inspection = Inspection.new
  end

  # GET /inspections/1/edit
  def edit
  end

  # POST /inspections
  # POST /inspections.json
  def create
    @inspection = Inspection.new(inspection_params)

    @inspection.user_id = current_user.id

    respond_to do |format|
      if @inspection.save
        format.html { redirect_to @inspection, notice: 'Inspection was successfully created.' }
        format.json { render :show, status: :created, location: @inspection }
      else
        format.html { render :new }
        format.json { render json: @inspection.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /inspections/1
  # PATCH/PUT /inspections/1.json
  def update
    respond_to do |format|
      if @inspection.update(inspection_params)
        format.html { redirect_to @inspection, notice: 'Inspection was successfully updated.' }
        format.json { render :show, status: :ok, location: @inspection }
      else
        format.html { render :edit }
        format.json { render json: @inspection.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /inspections/1
  # DELETE /inspections/1.json
  def destroy
    @inspection.destroy
    respond_to do |format|
      format.html { redirect_to inspections_url, notice: 'Inspection was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_inspection
      @inspection = Inspection.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def inspection_params
      params.require(:inspection).permit(:description, :unit_id, :building_id, :template_id, items_attributes: [:id, :score])
    end
end

app/helpers/inspections_helper.rb
module InspectionsHelper
end

app/views/inspections/_form.html.erb
<%= form_for(@inspection) do |f| %>
  <% if @inspection.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@inspection.errors.count, "error") %> prohibited this inspection from being saved:</h2>

      <ul>
      <% @inspection.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :unit_id %><br>
    <%= f.number_field :unit_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/inspections/edit.html.erb
<h1>Editing Inspection</h1>

<%= render 'form' %>

<%= link_to 'Show', @inspection %> |
<%= link_to 'Back', inspections_path %>

app/views/inspections/index.html.erb
<h1>Listing Inspections</h1>

<table>
  <thead>
    <tr>
      <th>Description</th>
      <th>Unit</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @inspections.each do |inspection| %>
      <tr>
        <td><%= inspection.description %></td>
        <td><%= inspection.unit_id %></td>
        <td><%= link_to 'Show', inspection %></td>
        <td><%= link_to 'Edit', edit_inspection_path(inspection) %></td>
        <td><%= link_to 'Destroy', inspection, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Inspection', new_inspection_path %>

app/views/inspections/new.html.erb
<h1>New Inspection</h1>

<%= render 'form' %>

<%= link_to 'Back', inspections_path %>

app/views/inspections/show.html.erb
<p>
  <strong>Description:</strong>
  <%= @inspection.description %>
</p>

<p>
  <strong>Unit:</strong>
  <%= @inspection.unit_id %>
</p>

<%= link_to 'Edit', edit_inspection_path(@inspection) %> |
<%= link_to 'Back', inspections_path %>