config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { registrations: 'registrations'}

  scope "/admin" do
    resources :users
  end

  resources :roles

  root to: "home#index"

  resources :inspections
  resources :buildings do 
    resources :units
  end
  resources :inspection_templates
  

end

app/views/layouts/_home_page.html.erb
<style type="text/css">
body{
    background-image: url("/assets/home_page_background.png");
    background-color: #444;
}
</style>

app/views/layouts/_nav.html.erb
<div class="nav-side-menu">
    <div class="brand"><strong><%= link_to 'BUILDING INSPECTIONATOR', root_url %></strong></div>
    <i class="fa fa-bars fa-2x toggle-btn" data-toggle="collapse" data-target="#menu-content"></i>
        <div class="menu-list">
          <ul id="menu-content" class="menu-content collapse out">
            <li data-toggle="collapse" data-target="#building" class="collapsed">
              <a href=""><i class="fa fa-building-o fa-2x"></i> <span class="menu-title">Buildings</span> <span class="arrow"></span></a>
            </li>  
            <ul class="sub-menu collapse" id="building">
              <% unless @recent_buildings.empty? %>
                <% @recent_buildings.each do |building| %>
                  <li><%= link_to building.name, '#' + building_path(building) %></li>
                <% end %>
              <% end %>
              <li><%= link_to "View your Buildings", "#" + buildings_path %></li>
            </ul>
            <li data-toggle="collapse" data-target="#inspection" class="collapsed">
              <a href=""><i class="fa fa-wpforms fa-2x"></i> <span class="menu-title">Inspections</span><span class="arrow"></span></a>
            </li>
            <ul class="sub-menu collapse" id="inspection">
              <% unless @recent_inspections.empty? %>
                <% @recent_inspections.each do |inspection| %>
                  <li><%= link_to "Inspection #{inspection.id}", '#' +inspection_path(inspection) %></li>
                <% end %>
              <% end %>
              <li><%= link_to "View More Inspections", '#' + inspections_path %></li>
            </ul>
            <li data-toggle="collapse" data-target="#inspection-template" class="collapsed">
              <a href=""><i class="fa fa-newspaper-o fa-2x"></i> <span class="menu-title">Inspection Template </span><span class="arrow"></span></a>
            </li>
            <ul class="sub-menu collapse" id="inspection-template">
              <% unless @recent_inspection_templates.empty? %>
                <% @recent_inspection_templates.each do |inspT| %>
                  <li><%= link_to inspT.name, '#' + inspection_template_path(inspT) %></li>
                <% end %>
              <% end %>
              <li><%= link_to "View your Inspection Templates", '#' + inspection_templates_path %></li>
            </ul>
            <li>
              <a href="#">
              <i class="fa fa-users fa-2x"></i><span class="menu-title"> Users </span><span class="arrow"></span></a>
            </li>
            <li data-toggle="collapse" data-target="#profile" class="collapsed">
              <a href="#"><i class="fa fa-user fa-2x"></i> <span class="menu-title">Profile</span> <span class="arrow"></span></a>
            </li>
            <ul class="sub-menu collapse" id="profile">
              <li><%= link_to "Edit profile", edit_user_registration_path %></li>
              <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
            </ul>
          </ul>
     </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Building Inspections</title>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css">
  <link href="https://fonts.googleapis.com/css?family=Oswald:700" rel="stylesheet">
  <script async defer src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GOOGLE_MAPS_API'] %>"  
  type="text/javascript"></script>
  
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>

<% if user_signed_in? %>
  <body ng-app="buildingInspections">
    <div class="container error-messages">
      <% flash.each do |name, msg| %>
        <%= content_tag(:div, class: "alert alert-#{name} #{flash_class(name)}") do%>
          <%=msg%>
          <button type="button" class="close" data-dismiss="alert">&times;</button>
        <% end %>
      <% end %>
    </div>
    <%= render 'layouts/nav' %>
    <div class="container">
      <div class="col-md-12">
        <%= yield %>
      </div>
    </div>
  </body>
<% else %>
  <body>
    <div class="container error-messages">
      <% flash.each do |name, msg| %>
        <%= content_tag(:div, class: "alert alert-#{name} #{flash_class(name)}") do%>
          <%=msg%>
          <button type="button" class="close" data-dismiss="alert">&times;</button>
        <% end %>
      <% end %>
    </div>
    <%= render 'layouts/home_page' %>
    <%= yield %>
  </body>
<% end %>
<footer class="container text-center">
		&copy; 2016 Incu-tech, LLC. 
		<br>
		<%= Rails.application.config.version_number + ' ' + Rails.application.config.version_date %>
</footer>
</html>